security:
    firewalls:
        main:
            guard:
                authenticators:
                    - ICS\SsiBundle\Security\KeycloakAuthenticator
                entry_point: ICS\SsiBundle\Security\KeycloakAuthenticator